In [1]:
import pandas as pd

In [2]:
df_16_9=pd.read_csv('./서울교통공사_9호선2-3단계역별일별시간대별승하차인원_20161231.csv', encoding='cp949')
df_17_9=pd.read_csv('./서울교통공사_9호선2-3단계역별일별시간대별승하차인원_20171231.csv', encoding='cp949')
df_18_9=pd.read_csv('./서울교통공사_9호선2-3단계역별일별시간대별승하차인원_20181231.csv', encoding='cp949')
df_19_9=pd.read_csv('./서울교통공사_9호선2-3단계역별일별시간대별승하차인원_20191231.csv', encoding='cp949')
df_20_9=pd.read_csv('./서울교통공사_9호선2-3단계역별일별시간대별승하차인원_20201231.csv', encoding='cp949')
df_21_9=pd.read_csv('./서울교통공사_9호선2_3단계 역별일별시간대별승하차인원_20211231.csv', encoding='cp949')

In [3]:
df_16_9['호선'] = df_16_9['호선'].apply(lambda x : x[0]) # '9호선' -> '9'로 변경

# 합쳐질 데이터와 column명 통일화
df_16_9_to5 = df_16_9[['00~01','01~02','02~03','03~04','04~05','23~24']] 
df_16_9['23~'] = df_16_9_to5.sum(axis='columns')

# 필요없는 column 삭제
df_16_9.drop(columns=['역번호', '00~01','01~02','02~03','03~04','04~05','23~24'], inplace=True)

df_16_9['구분'] = df_16_9['구분'].apply(lambda x : x[-2:]) # '구분' column을 '승차', '하차'로 변경

df_16_9.head()

# 순승차와 환승승차, 순하차와 환승하차 병합
for i in range(0, len(df_16_9)-1, 2):
    if df_16_9.loc[i]['구분'] == df_16_9.loc[i+1]['구분']:
        df_16_9.loc[i] = df_16_9.loc[i] + df_16_9.loc[i+1]
        
        day = df_16_9.loc[i, '날짜'][:10]
        df_16_9.loc[i, '날짜'] = day
        
        df_16_9.loc[i, '호선'] = '9'
        
        station_len = int(len(df_16_9.loc[i, '역명'])/2)
        station = df_16_9.loc[i, '역명'][:station_len]
        df_16_9.loc[i, '역명'] = station
        
        dist = df_16_9.loc[i, '구분'][:2]
        df_16_9.loc[i, '구분'] = dist
        
        df_16_9.drop(index = i+1, inplace=True)

# 인덱스 정리
df_16_9 = df_16_9.set_index('날짜').reset_index()

In [4]:
df_17_9=df_17_9.dropna(axis='index')

In [5]:
df_17_9['호선'] = df_17_9['호선'].apply(lambda x : x[0]) # '9호선' -> '9'로 변경

# 합쳐질 데이터와 column명 통일화
df_17_9_to5 = df_17_9[['00~01','01~02','02~03','03~04','04~05','23~24']] 
df_17_9['23~'] = df_17_9_to5.sum(axis='columns')

# 필요없는 column 삭제
df_17_9.drop(columns=['역번호', '00~01','01~02','02~03','03~04','04~05','23~24'], inplace=True)

df_17_9['구분'] = df_17_9['구분'].apply(lambda x : x[-2:]) # '구분' column을 '승차', '하차'로 변경

df_17_9.head()

# 순승차와 환승승차, 순하차와 환승하차 병합
for i in range(0, len(df_17_9)-1, 2):
    if df_17_9.loc[i]['구분'] == df_17_9.loc[i+1]['구분']:
        df_17_9.loc[i] = df_17_9.loc[i] + df_17_9.loc[i+1]
        
        day = df_17_9.loc[i, '날짜'][:10]
        df_17_9.loc[i, '날짜'] = day
        
        df_17_9.loc[i, '호선'] = '9'
        
        station_len = int(len(df_17_9.loc[i, '역명'])/2)
        station = df_17_9.loc[i, '역명'][:station_len]
        df_17_9.loc[i, '역명'] = station
        
        dist = df_17_9.loc[i, '구분'][:2]
        df_17_9.loc[i, '구분'] = dist
        
        df_17_9.drop(index = i+1, inplace=True)

# 인덱스 정리
df_17_9 = df_17_9.set_index('날짜').reset_index()

In [6]:
df_18_9['호선'] = df_18_9['호선'].apply(lambda x : x[0]) # '9호선' -> '9'로 변경

# 합쳐질 데이터와 column명 통일화
df_18_9_to5 = df_18_9[['00~01','01~02','02~03','03~04','04~05','23~24']] 
df_18_9['23~'] = df_18_9_to5.sum(axis='columns')

# 필요없는 column 삭제
df_18_9.drop(columns=['역번호', '00~01','01~02','02~03','03~04','04~05','23~24'], inplace=True)

df_18_9['구분'] = df_18_9['구분'].apply(lambda x : x[-2:]) # '구분' column을 '승차', '하차'로 변경

df_18_9.head()

# 순승차와 환승승차, 순하차와 환승하차 병합
for i in range(0, len(df_18_9)-1, 2):
    if df_18_9.loc[i]['구분'] == df_18_9.loc[i+1]['구분']:
        df_18_9.loc[i] = df_18_9.loc[i] + df_18_9.loc[i+1]
        
        day = df_18_9.loc[i, '날짜'][:10]
        df_18_9.loc[i, '날짜'] = day
        
        df_18_9.loc[i, '호선'] = '9'
        
        station_len = int(len(df_18_9.loc[i, '역명'])/2)
        station = df_18_9.loc[i, '역명'][:station_len]
        df_18_9.loc[i, '역명'] = station
        
        dist = df_18_9.loc[i, '구분'][:2]
        df_18_9.loc[i, '구분'] = dist
        
        df_18_9.drop(index = i+1, inplace=True)

# 인덱스 정리
df_18_9 = df_18_9.set_index('날짜').reset_index()

In [7]:
df_19_9['호선'] = df_19_9['호선'].apply(lambda x : x[0]) # '9호선' -> '9'로 변경

# 합쳐질 데이터와 column명 통일화
df_19_9_to5 = df_19_9[['00~01','01~02','02~03','03~04','04~05','23~24']] 
df_19_9['23~'] = df_19_9_to5.sum(axis='columns')

# 필요없는 column 삭제
df_19_9.drop(columns=['역번호', '00~01','01~02','02~03','03~04','04~05','23~24'], inplace=True)

df_19_9['구분'] = df_19_9['구분'].apply(lambda x : x[-2:]) # '구분' column을 '승차', '하차'로 변경

df_19_9.head()

# 순승차와 환승승차, 순하차와 환승하차 병합
for i in range(0, len(df_19_9)-1, 2):
    if df_19_9.loc[i]['구분'] == df_19_9.loc[i+1]['구분']:
        df_19_9.loc[i] = df_19_9.loc[i] + df_19_9.loc[i+1]
        
        day = df_19_9.loc[i, '날짜'][:10]
        df_19_9.loc[i, '날짜'] = day
        
        df_19_9.loc[i, '호선'] = '9'
        
        station_len = int(len(df_19_9.loc[i, '역명'])/2)
        station = df_19_9.loc[i, '역명'][:station_len]
        df_19_9.loc[i, '역명'] = station
        
        dist = df_19_9.loc[i, '구분'][:2]
        df_19_9.loc[i, '구분'] = dist
        
        df_19_9.drop(index = i+1, inplace=True)

# 인덱스 정리
df_19_9 = df_19_9.set_index('날짜').reset_index()

In [8]:
df_20_9['호선'] = df_20_9['호선'].apply(lambda x : x[0]) # '9호선' -> '9'로 변경

# 합쳐질 데이터와 column명 통일화
df_20_9_to5 = df_20_9[['00~01','01~02','02~03','03~04','04~05','23~24']] 
df_20_9['23~'] = df_20_9_to5.sum(axis='columns')

# 필요없는 column 삭제
df_20_9.drop(columns=['역번호', '00~01','01~02','02~03','03~04','04~05','23~24'], inplace=True)

df_20_9['구분'] = df_20_9['구분'].apply(lambda x : x[-2:]) # '구분' column을 '승차', '하차'로 변경

df_20_9.head()

# 순승차와 환승승차, 순하차와 환승하차 병합
for i in range(0, len(df_20_9)-1, 2):
    if df_20_9.loc[i]['구분'] == df_20_9.loc[i+1]['구분']:
        df_20_9.loc[i] = df_20_9.loc[i] + df_20_9.loc[i+1]
        
        day = df_20_9.loc[i, '날짜'][:10]
        df_20_9.loc[i, '날짜'] = day
        
        df_20_9.loc[i, '호선'] = '9'
        
        station_len = int(len(df_20_9.loc[i, '역명'])/2)
        station = df_20_9.loc[i, '역명'][:station_len]
        df_20_9.loc[i, '역명'] = station
        
        dist = df_20_9.loc[i, '구분'][:2]
        df_20_9.loc[i, '구분'] = dist
        
        df_20_9.drop(index = i+1, inplace=True)

# 인덱스 정리
df_20_9 = df_20_9.set_index('날짜').reset_index()

In [9]:
# 합쳐질 데이터와 column명 통일화
df_21_9_to5 = df_21_9[['00시-01시','01시-02시','02시-03시','03시-04시','04시-05시','23시-24시']] 
df_21_9['23~'] = df_21_9_to5.sum(axis='columns')

# 필요없는 column 삭제
df_21_9.drop(columns=['연번','역번호', '00시-01시','01시-02시','02시-03시','03시-04시','04시-05시','23시-24시'], inplace=True)

df_21_9['구분'] = df_21_9['구분'].apply(lambda x : x[-2:]) # '구분' column을 '승차', '하차'로 변경
df_21_9.columns=['날짜','호선','역명','구분','05~06','06~07','07~08','08~09','09~10','10~11',
                 '11~12','12~13','13~14','14~15','15~16','16~17','17~18','18~19','19~20','20~21','21~22','22~23','23~']

df_21_9.head()

# 순승차와 환승승차, 순하차와 환승하차 병합
for i in range(0, len(df_21_9)-1, 2):
    if df_21_9.loc[i]['구분'] == df_21_9.loc[i+1]['구분']:
        df_21_9.loc[i] = df_21_9.loc[i] + df_21_9.loc[i+1]
        
        day = df_21_9.loc[i, '날짜'][:10]
        df_21_9.loc[i, '날짜'] = day
        
        df_21_9.loc[i, '호선'] = '9'
        
        station_len = int(len(df_21_9.loc[i, '역명'])/2)
        station = df_21_9.loc[i, '역명'][:station_len]
        df_21_9.loc[i, '역명'] = station
        
        dist = df_21_9.loc[i, '구분'][:2]
        df_21_9.loc[i, '구분'] = dist
        
        df_21_9.drop(index = i+1, inplace=True)

# 인덱스 정리
df_21_9 = df_21_9.set_index('날짜').reset_index()

In [10]:
df_21_9

,날짜,호선,역명,구분,05~06,06~07,07~08,08~09,09~10,10~11,...,14~15,15~16,16~17,17~18,18~19,19~20,20~21,21~22,22~23,23~
0,2021-01-01,9,언주,승차,19,39,60,58,46,67,...,90,129,125,124,100,67,90,71,64,11
1,2021-01-01,9,언주,하차,8,69,60,67,87,71,...,86,98,91,111,84,74,70,90,46,27
2,2021-01-02,9,언주,승차,17,37,59,84,108,147,...,213,237,255,214,162,129,117,117,79,22
3,2021-01-02,9,언주,하차,14,130,147,248,248,186,...,190,171,138,173,121,100,108,111,58,32
4,2021-01-03,9,언주,승차,9,26,52,47,54,64,...,128,141,137,152,118,103,105,104,67,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9485,2021-12-29,9,중앙보훈병원,하차,24,307,455,750,485,430,...,363,387,387,566,1045,867,442,758,417,107
9486,2021-12-30,9,중앙보훈병원,승차,103,443,1509,1365,863,650,...,570,604,587,686,456,139,104,90,94,13
9487,2021-12-30,9,중앙보훈병원,하차,26,287,404,748,525,460,...,374,322,350,516,1006,797,458,645,433,101
9488,2021-12-31,9,중앙보훈병원,승차,74,347,1211,1108,644,615,...,495,504,457,559,301,115,97,76,90,7
9489,2021-12-31,9,중앙보훈병원,하차,19,153,305,580,414,344,...,385,403,517,651,700,525,305,440,326,66

In [11]:
df=df_16_9.append(df_17_9)
df=df.append(df_18_9)
df=df.append(df_19_9)
df=df.append(df_20_9)
df=df.append(df_21_9)

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_872\3222740338.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df_16_9.append(df_17_9)
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_872\3222740338.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(df_18_9)
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_872\3222740338.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(df_19_9)
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_872\3222740338.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(df_20_9)
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_872\3222740338.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(df_21_9)

In [12]:
df.to_csv('서울교통공사_9호선일별역별시간대별승하차인원_(2016~2021년).csv', index=False)