In [1]:
import pandas as pd

In [2]:
df_1=pd.read_csv('./서울교통공사_혼잡도_20171231.csv', encoding='cp949')
df_2=pd.read_csv('./서울교통공사_혼잡도_20191231.csv', encoding='cp949')
df_3=pd.read_csv('./서울교통공사_혼잡도_20211231.csv', encoding='cp949')

In [3]:
# 컬럼: 조사일자, 호선('~호선'), 역명, 방향, 5시30분(%)~23시30분(%)로 변경
df_1.drop(columns=['호선','24:00~ (%)','24:30~ (%)'], inplace=True)
df_2.drop(columns=['호선','24시00분', '24시30분'], inplace=True)
df_3.drop(columns=['연번','호선'], inplace=True)

In [4]:
# 호선 열 재생성
df_1['호선']=0
df_2['호선']=0
df_3['호선']=0
for i in range(0, len(df_1)):
    if len(str(df_1.iloc[i]['역번호']))==3:
        df_1.loc[i, '호선']=str(df_1.iloc[i]['역번호'])[0]+'호선'
    else:
        df_1.loc[i, '호선']=str(df_1.iloc[i]['역번호'])[1]+'호선'
        
for i in range(0, len(df_2)):
    if len(str(df_2.iloc[i]['역번호']))==3:
        df_2.loc[i, '호선']=str(df_2.iloc[i]['역번호'])[0]+'호선'
    else:
        df_2.loc[i, '호선']=str(df_2.iloc[i]['역번호'])[1]+'호선'
        
for i in range(0, len(df_3)):
    if len(str(df_3.iloc[i]['역번호']))==3:
        df_3.loc[i, '호선']=str(df_3.iloc[i]['역번호'])[0]+'호선'
    else:
        df_3.loc[i, '호선']=str(df_3.iloc[i]['역번호'])[1]+'호선'

# 역번호 열 제거
df_1.drop(columns=['역번호'], inplace=True)
df_2.drop(columns=['역번호'], inplace=True)
df_3.drop(columns=['역번호'], inplace=True)

In [5]:
# 조사연도 추가
df_1['조사연도']=2017
df_2['조사연도']=2019
df_3['조사연도']=2021

In [6]:
# # 칼럼 이름 통합
# df_1.columns=['조사일자', '역명', '방향', '5시30분~ (%)', '6시00분~ (%)', '6시30분~ (%)',
#        '7시00분~ (%)', '7시30분~ (%)', '8시00분~ (%)', '8시30분~ (%)', '9시00분~ (%)',
#        '9시30분~ (%)', '10시00분~ (%)', '10시30분~ (%)', '11시00분~ (%)', '11시30분~ (%)',
#        '12시00분~ (%)', '12시30분~ (%)', '13시00분~ (%)', '13시30분~ (%)', '14시00분~ (%)',
#        '14시30분~ (%)', '15시00분~ (%)', '15시30분~ (%)', '16시00분~ (%)', '16시30분~ (%)',
#        '17시00분~ (%)', '17시30분~ (%)', '18시00분~ (%)', '18시30분~ (%)', '19시00분~ (%)',
#        '19시30분~ (%)', '20시00분~ (%)', '20시30분~ (%)', '21시00분~ (%)', '21시30분~ (%)',
#        '22시00분~ (%)', '22시30분~ (%)', '23시00분~ (%)', '23시30분~ (%)', '호선','조사연도']
# df_2.columns=['조사일자', '역명', '방향', '5시30분~ (%)', '6시00분~ (%)', '6시30분~ (%)',
#        '7시00분~ (%)', '7시30분~ (%)', '8시00분~ (%)', '8시30분~ (%)', '9시00분~ (%)',
#        '9시30분~ (%)', '10시00분~ (%)', '10시30분~ (%)', '11시00분~ (%)', '11시30분~ (%)',
#        '12시00분~ (%)', '12시30분~ (%)', '13시00분~ (%)', '13시30분~ (%)', '14시00분~ (%)',
#        '14시30분~ (%)', '15시00분~ (%)', '15시30분~ (%)', '16시00분~ (%)', '16시30분~ (%)',
#        '17시00분~ (%)', '17시30분~ (%)', '18시00분~ (%)', '18시30분~ (%)', '19시00분~ (%)',
#        '19시30분~ (%)', '20시00분~ (%)', '20시30분~ (%)', '21시00분~ (%)', '21시30분~ (%)',
#        '22시00분~ (%)', '22시30분~ (%)', '23시00분~ (%)', '23시30분~ (%)', '호선','조사연도']
# df_3.columns=['조사일자', '역명', '방향', '5시30분~ (%)', '6시00분~ (%)', '6시30분~ (%)',
#        '7시00분~ (%)', '7시30분~ (%)', '8시00분~ (%)', '8시30분~ (%)', '9시00분~ (%)',
#        '9시30분~ (%)', '10시00분~ (%)', '10시30분~ (%)', '11시00분~ (%)', '11시30분~ (%)',
#        '12시00분~ (%)', '12시30분~ (%)', '13시00분~ (%)', '13시30분~ (%)', '14시00분~ (%)',
#        '14시30분~ (%)', '15시00분~ (%)', '15시30분~ (%)', '16시00분~ (%)', '16시30분~ (%)',
#        '17시00분~ (%)', '17시30분~ (%)', '18시00분~ (%)', '18시30분~ (%)', '19시00분~ (%)',
#        '19시30분~ (%)', '20시00분~ (%)', '20시30분~ (%)', '21시00분~ (%)', '21시30분~ (%)',
#        '22시00분~ (%)', '22시30분~ (%)', '23시00분~ (%)', '23시30분~ (%)', '호선','조사연도']

In [7]:
for i in range(1,4):
    globals()[f'df_{i}'].columns=['조사일자', '역명', '방향', '5시30분~ (%)', '6시00분~ (%)', '6시30분~ (%)',
       '7시00분~ (%)', '7시30분~ (%)', '8시00분~ (%)', '8시30분~ (%)', '9시00분~ (%)',
       '9시30분~ (%)', '10시00분~ (%)', '10시30분~ (%)', '11시00분~ (%)', '11시30분~ (%)',
       '12시00분~ (%)', '12시30분~ (%)', '13시00분~ (%)', '13시30분~ (%)', '14시00분~ (%)',
       '14시30분~ (%)', '15시00분~ (%)', '15시30분~ (%)', '16시00분~ (%)', '16시30분~ (%)',
       '17시00분~ (%)', '17시30분~ (%)', '18시00분~ (%)', '18시30분~ (%)', '19시00분~ (%)',
       '19시30분~ (%)', '20시00분~ (%)', '20시30분~ (%)', '21시00분~ (%)', '21시30분~ (%)',
       '22시00분~ (%)', '22시30분~ (%)', '23시00분~ (%)', '23시30분~ (%)', '호선','조사연도']

In [8]:
# 컬럼 순서 교체
df_1=df_1[['조사연도', '조사일자', '호선', '역명', '방향', '5시30분~ (%)', '6시00분~ (%)', '6시30분~ (%)',
       '7시00분~ (%)', '7시30분~ (%)', '8시00분~ (%)', '8시30분~ (%)', '9시00분~ (%)',
       '9시30분~ (%)', '10시00분~ (%)', '10시30분~ (%)', '11시00분~ (%)', '11시30분~ (%)',
       '12시00분~ (%)', '12시30분~ (%)', '13시00분~ (%)', '13시30분~ (%)', '14시00분~ (%)',
       '14시30분~ (%)', '15시00분~ (%)', '15시30분~ (%)', '16시00분~ (%)', '16시30분~ (%)',
       '17시00분~ (%)', '17시30분~ (%)', '18시00분~ (%)', '18시30분~ (%)', '19시00분~ (%)',
       '19시30분~ (%)', '20시00분~ (%)', '20시30분~ (%)', '21시00분~ (%)', '21시30분~ (%)',
       '22시00분~ (%)', '22시30분~ (%)', '23시00분~ (%)', '23시30분~ (%)']]
df_2=df_2[['조사연도','조사일자', '호선', '역명', '방향', '5시30분~ (%)', '6시00분~ (%)', '6시30분~ (%)',
       '7시00분~ (%)', '7시30분~ (%)', '8시00분~ (%)', '8시30분~ (%)', '9시00분~ (%)',
       '9시30분~ (%)', '10시00분~ (%)', '10시30분~ (%)', '11시00분~ (%)', '11시30분~ (%)',
       '12시00분~ (%)', '12시30분~ (%)', '13시00분~ (%)', '13시30분~ (%)', '14시00분~ (%)',
       '14시30분~ (%)', '15시00분~ (%)', '15시30분~ (%)', '16시00분~ (%)', '16시30분~ (%)',
       '17시00분~ (%)', '17시30분~ (%)', '18시00분~ (%)', '18시30분~ (%)', '19시00분~ (%)',
       '19시30분~ (%)', '20시00분~ (%)', '20시30분~ (%)', '21시00분~ (%)', '21시30분~ (%)',
       '22시00분~ (%)', '22시30분~ (%)', '23시00분~ (%)', '23시30분~ (%)']]
df_3=df_3[['조사연도','조사일자', '호선', '역명', '방향', '5시30분~ (%)', '6시00분~ (%)', '6시30분~ (%)',
       '7시00분~ (%)', '7시30분~ (%)', '8시00분~ (%)', '8시30분~ (%)', '9시00분~ (%)',
       '9시30분~ (%)', '10시00분~ (%)', '10시30분~ (%)', '11시00분~ (%)', '11시30분~ (%)',
       '12시00분~ (%)', '12시30분~ (%)', '13시00분~ (%)', '13시30분~ (%)', '14시00분~ (%)',
       '14시30분~ (%)', '15시00분~ (%)', '15시30분~ (%)', '16시00분~ (%)', '16시30분~ (%)',
       '17시00분~ (%)', '17시30분~ (%)', '18시00분~ (%)', '18시30분~ (%)', '19시00분~ (%)',
       '19시30분~ (%)', '20시00분~ (%)', '20시30분~ (%)', '21시00분~ (%)', '21시30분~ (%)',
       '22시00분~ (%)', '22시30분~ (%)', '23시00분~ (%)', '23시30분~ (%)']]

In [9]:
# 오류 데이터 변경
df_1.replace('0호선','5호선', inplace=True)

In [10]:
# 데이터 결합(2017 평일 1~8호선, 2017 토요일 1~8호선, 2017 1~8호선 일요일, 2019 ~~ , 2021~~ 순서)
df_1.sort_values(by=['조사일자','호선','역명'], axis=0, ascending=True, inplace=True)
df_2.sort_values(by=['조사일자','호선','역명'], axis=0, ascending=True, inplace=True)
df_3.sort_values(by=['조사일자','호선','역명'], axis=0, ascending=True, inplace=True)
df_conf=pd.concat([df_1,df_2,df_3], axis=0)

In [11]:
df_conf=df_conf.reset_index()

In [12]:
df_conf.drop(columns='index', inplace=True)

In [13]:
# null값 0으로 대체
df_conf.replace(' ', '0.0', inplace=True)

In [14]:
df_conf.iloc[:,5:]=df_conf.iloc[:,5:].astype(float)

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\1217214773.py:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_conf.iloc[:,5:]=df_conf.iloc[:,5:].astype(float)

In [15]:
df_conf['출근시간대 혼잡도'] = df_conf.iloc[:,8:14].mean(axis=1)

In [16]:
df_conf['퇴근시간대 혼잡도'] = df_conf.iloc[:,28:34].mean(axis=1)

In [17]:
df_conf

,조사연도,조사일자,호선,역명,방향,5시30분~ (%),6시00분~ (%),6시30분~ (%),7시00분~ (%),7시30분~ (%),...,20시00분~ (%),20시30분~ (%),21시00분~ (%),21시30분~ (%),22시00분~ (%),22시30분~ (%),23시00분~ (%),23시30분~ (%),출근시간대 혼잡도,퇴근시간대 혼잡도
0,2017,일요일,1호선,동대문,상선,4.8,7.8,7.8,9.3,12.7,...,26.1,22.0,27.2,26.2,27.8,29.1,18.0,13.2,11.866667,30.150000
1,2017,일요일,1호선,동대문,하선,8.4,9.6,8.6,8.5,9.7,...,13.6,9.7,13.6,15.0,11.2,10.2,7.8,5.0,17.300000,26.650000
2,2017,일요일,1호선,동묘앞,상선,3.7,8.5,7.7,9.1,12.5,...,23.5,20.5,25.0,22.8,25.7,25.7,15.3,13.2,10.933333,28.450000
3,2017,일요일,1호선,동묘앞,하선,8.1,9.7,9.4,8.8,10.7,...,12.7,10.2,16.2,11.0,8.9,11.5,6.8,4.9,18.300000,26.683333
4,2017,일요일,1호선,서울역,상선,4.2,7.9,9.5,11.8,11.8,...,16.8,16.9,17.9,18.7,20.7,20.6,12.1,10.6,16.466667,23.083333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5035,2021,평일,8호선,잠실,하선,22.0,31.6,41.5,52.2,74.2,...,37.0,30.5,38.9,32.5,40.4,33.4,24.6,18.2,72.233333,62.700000
5036,2021,평일,8호선,장지,상선,34.2,22.5,28.3,44.2,67.8,...,25.0,22.3,21.3,18.1,19.5,16.1,15.8,6.0,73.566667,46.650000
5037,2021,평일,8호선,장지,하선,14.0,18.1,21.4,28.3,33.9,...,31.7,29.1,31.9,29.8,33.6,29.6,21.0,16.1,30.883333,55.916667
5038,2021,평일,8호선,천호,상선,2.3,2.7,3.5,2.7,3.4,...,16.3,14.8,13.6,14.7,14.2,14.5,11.3,10.0,5.750000,24.983333
5039,2021,평일,8호선,천호,하선,23.5,29.8,45.8,57.4,79.2,...,15.1,12.8,14.6,12.1,15.4,11.7,10.2,5.7,83.716667,29.683333

 ## 7-10시, 17-20시의 호선별 승하차인원수 TOP1 역의 혼잡도

### 혼잡도 기준: 36% = 모든 좌석에 승객이 앉아있고 입석자가 없는 경우

- 역: 출근시간대/퇴근시간대
- 영등포: 데이터 없음
- 강남: 평일, 외선/평일, 내선
- 고속터미널: 평일, 하선/평일, 상선
- 혜화: 평일, 하선/평일, 상선
- 광화문: 평일, 상선/평일, 하선
- 응암: 평일, 하선/평일, 상선
- 가산디지털단지: 평일, 상선/평일, 하선
- 암사: 평일, 하선/평일, 하선
- 천호: 평일, 상선/평일, 하선
- 신논현: 데이터 없음

In [18]:
df_conf.loc[(df_conf['역명']=='강남') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='외선')]

,조사연도,조사일자,호선,역명,방향,5시30분~ (%),6시00분~ (%),6시30분~ (%),7시00분~ (%),7시30분~ (%),...,20시00분~ (%),20시30분~ (%),21시00분~ (%),21시30분~ (%),22시00분~ (%),22시30분~ (%),23시00분~ (%),23시30분~ (%),출근시간대 혼잡도,퇴근시간대 혼잡도
1133,2017,평일,2호선,강남,외선,59.3,33.0,36.1,59.5,83.0,...,50.4,42.0,51.4,63.6,73.8,51.9,50.7,37.3,89.350000,61.966667
2801,2019,평일,2호선,강남,외선,44.4,29.2,38.6,54.8,78.5,...,49.2,39.5,46.5,56.6,61.5,50.2,39.5,31.6,91.300000,59.716667
4493,2021,평일,2호선,강남,외선,52.4,27.1,35.1,56.9,68.8,...,32.8,26.3,39.5,38.8,55.5,45.8,45.0,28.1,81.233333,47.750000

In [19]:
# 호선별 승하차인원이 가장 많은 역의 필요한 데이터 추출
df_conf_2_g=df_conf[(df_conf['역명']=='강남') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='외선')]
df_conf_2_l=df_conf[(df_conf['역명']=='강남') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='내선')]
df_conf_3_g=df_conf[(df_conf['역명']=='고속터미널') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='하선')]
df_conf_3_l=df_conf[(df_conf['역명']=='고속터미널') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='상선')]
df_conf_4_g=df_conf[(df_conf['역명']=='혜화') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='하선')]
df_conf_4_l=df_conf[(df_conf['역명']=='혜화') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='상선')]
df_conf_5_g=df_conf[(df_conf['역명']=='광화문') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='상선')]
df_conf_5_l=df_conf[(df_conf['역명']=='광화문') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='하선')]
df_conf_6_g=df_conf[(df_conf['역명']=='응암') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='하선')]
df_conf_6_l=df_conf[(df_conf['역명']=='응암') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='상선')]
df_conf_7_g=df_conf[(df_conf['역명']=='가산디지털단지') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='상선')]
df_conf_7_l=df_conf[(df_conf['역명']=='가산디지털단지') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='하선')]
df_conf_8_g=df_conf[(df_conf['역명']=='암사') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='하선')]
df_conf_8_l=df_conf[(df_conf['역명']=='암사') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='하선')]
df_conf_9_g=df_conf[(df_conf['역명']=='천호') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='상선')]
df_conf_9_l=df_conf[(df_conf['역명']=='천호') & (df_conf['조사일자']=='평일') & (df_conf['방향']=='하선')]

In [20]:
# 호선별 승하차인원이 가장 많은 역의 출근 시간대 혼잡도
for i in range(2,10):
    globals()[f'df_conf_{i}_g']=globals()[f'df_conf_{i}_g'].loc[:,['호선','역명','출근시간대 혼잡도']]

In [21]:
# 호선별 승하차인원이 가장 많은 역의 출근시간대 혼잡도 3년 평균
for i in range(2,10):
    globals()[f'df_conf_{i}_g']=globals()[f'df_conf_{i}_g'].groupby(by=['호선','역명']).mean()

In [22]:
# 호선별 승하차인원이 가장 많은 역의 퇴근 시간대 혼잡도
for i in range(2,10):
    globals()[f'df_conf_{i}_l']=globals()[f'df_conf_{i}_l'].loc[:,['호선','역명','퇴근시간대 혼잡도']]

In [23]:
# 호선별 승하차인원이 가장 많은 역의 퇴근시간대 혼잡도 3년 평균
for i in range(2,10):
    globals()[f'df_conf_{i}_l']=globals()[f'df_conf_{i}_l'].groupby(by=['호선','역명']).mean()

In [24]:
# 호선별 승하차인원이 가장 많은 역의 출근시간대 혼잡도 데이터프레임으로 나타내기
df_conf_g=pd.DataFrame(df_conf_2_g.reset_index())
for i in range(3,10):
    df_conf_g=df_conf_g.append(pd.DataFrame(globals()[f'df_conf_{i}_g'].reset_index()))
    
df_conf_g=df_conf_g.reset_index().drop(columns='index')
df_conf_g=df_conf_g.drop([2,8])

df_conf_g

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\3679070001.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_g=df_conf_g.append(pd.DataFrame(globals()[f'df_conf_{i}_g'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\3679070001.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_g=df_conf_g.append(pd.DataFrame(globals()[f'df_conf_{i}_g'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\3679070001.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_g=df_conf_g.append(pd.DataFrame(globals()[f'df_conf_{i}_g'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\3679070001.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_g=df_conf_g.append(pd.DataFrame(globals()[f'df_conf_{i}_g'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\3679070001.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_g=df_conf_g.append(pd.DataFrame(globals()[f'df_conf_{i}_g'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\3679070001.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_g=df_conf_g.append(pd.DataFrame(globals()[f'df_conf_{i}_g'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\3679070001.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_g=df_conf_g.append(pd.DataFrame(globals()[f'df_conf_{i}_g'].reset_index()))

    호선       역명   출근시간대 혼잡도
0  2호선       강남   87.294444
1  3호선    고속터미널   79.577778
3  4호선       혜화  104.955556
4  5호선      광화문   40.422222
5  6호선       응암   40.694444
6  7호선  가산디지털단지   72.883333
7  8호선       암사   33.938889
9  8호선       천호    5.855556

In [25]:
# 호선별 승하차인원이 가장 많은 역의 퇴근시간대 혼잡도 데이터프레임으로 나타내기
df_conf_l=pd.DataFrame(df_conf_2_l.reset_index())
for i in range(3,10):
    df_conf_l=df_conf_l.append(pd.DataFrame(globals()[f'df_conf_{i}_l'].reset_index()))
    
df_conf_l=df_conf_l.reset_index().drop(columns='index')
df_conf_l=df_conf_l.drop([2,8])

df_conf_l

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\4278339645.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_l=df_conf_l.append(pd.DataFrame(globals()[f'df_conf_{i}_l'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\4278339645.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_l=df_conf_l.append(pd.DataFrame(globals()[f'df_conf_{i}_l'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\4278339645.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_l=df_conf_l.append(pd.DataFrame(globals()[f'df_conf_{i}_l'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\4278339645.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_l=df_conf_l.append(pd.DataFrame(globals()[f'df_conf_{i}_l'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\4278339645.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_l=df_conf_l.append(pd.DataFrame(globals()[f'df_conf_{i}_l'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\4278339645.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_l=df_conf_l.append(pd.DataFrame(globals()[f'df_conf_{i}_l'].reset_index()))
C:\Users\tjoeun\AppData\Local\Temp\ipykernel_8716\4278339645.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_conf_l=df_conf_l.append(pd.DataFrame(globals()[f'df_conf_{i}_l'].reset_index()))

    호선       역명   퇴근시간대 혼잡도
0  2호선       강남  104.416667
1  3호선    고속터미널   74.850000
3  4호선       혜화  102.061111
4  5호선      광화문   57.255556
5  6호선       응암   28.594444
6  7호선  가산디지털단지   97.511111
7  8호선       암사    9.438889
9  8호선       천호   33.650000